In [1]:
# import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import nltk library
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter
stop_words = nltk.corpus.stopwords.words('english')

# import necessary libraries for text preprocessing
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split

In [3]:
doc1 = "The quick brown fox"
doc2 = "Jumped over the lazy dog"
doc3 = "The dog chased the fox"

corpus = [doc1, doc2, doc3]

In [9]:
# create bow model
# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(corpus)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(corpus)
# summarize encoded vector
print(vector.toarray())


{'the': 8, 'quick': 7, 'brown': 0, 'fox': 3, 'jumped': 4, 'over': 6, 'lazy': 5, 'dog': 2, 'chased': 1}
[[1 0 0 1 0 0 0 1 1]
 [0 0 1 0 1 1 1 0 1]
 [0 1 1 1 0 0 0 0 2]]


In [11]:
words = vectorizer.get_feature_names_out()
df_words = pd.DataFrame(vector.toarray(), columns=words)
print(df_words)


   brown  chased  dog  fox  jumped  lazy  over  quick  the
0      1       0    0    1       0     0     0      1    1
1      0       0    1    0       1     1     1      0    1
2      0       1    1    1       0     0     0      0    2


In [12]:
# create tf-idf model and the dataframe with words
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(corpus)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform(corpus)
# summarize encoded vector
print(vector.toarray())

words = vectorizer.get_feature_names_out()
df_words = pd.DataFrame(vector.toarray(), columns=words)
print(df_words)


{'the': 8, 'quick': 7, 'brown': 0, 'fox': 3, 'jumped': 4, 'over': 6, 'lazy': 5, 'dog': 2, 'chased': 1}
[1.69314718 1.69314718 1.28768207 1.28768207 1.69314718 1.69314718
 1.69314718 1.69314718 1.        ]
[[0.5844829  0.         0.         0.44451431 0.         0.
  0.         0.5844829  0.34520502]
 [0.         0.         0.38376993 0.         0.50461134 0.50461134
  0.50461134 0.         0.29803159]
 [0.         0.53058735 0.40352536 0.40352536 0.         0.
  0.         0.         0.62674687]]
      brown    chased       dog       fox    jumped      lazy      over  \
0  0.584483  0.000000  0.000000  0.444514  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.383770  0.000000  0.504611  0.504611  0.504611   
2  0.000000  0.530587  0.403525  0.403525  0.000000  0.000000  0.000000   

      quick       the  
0  0.584483  0.345205  
1  0.000000  0.298032  
2  0.000000  0.626747  
